<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="<?php echo $this->url('application.home'); ?>">
                <img src="<?php echo $this->basePath('asset/img/jf-logo-32x32.png'); ?>" width="30" height="30" class="d-inline-block align-top" alt="">
                JiNexus Framework
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main-content" aria-controls="navbar-main-content" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar-main-content">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="<?php echo $this->url('application.home'); ?>">Home <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>