<main role="main">
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3 d-none d-sm-block">Welcome to <span class="text-primary">JiNexus Framework</span></h1>
            <h3 class="d-block d-sm-none">Welcome to <span class="text-primary">JiNexus Framework</span></h3>
            <p>
                Congratulations! You have successfully installed the <a href="https://github.com/jinexus-framework/jinexus-framework-skeleton" target="_blank">JiNexus Framework Skeleton</a>.
                JiNexus Framework is a modular, lightweight and easy to use <a href="http://php.net/" target="_blank">PHP</a> framework and probably the smallest and fastest MVC framework that you'll ever use.
                You are currently running JiNexus Framework version <?php echo \Application\Module::VERSION; ?>.
                This skeleton can serve as a simple starting point for you to begin building your application with JiNexus Framework.
            </p>
            <p>
                <a class="btn btn-primary btn-lg" href="https://github.com/jinexus-framework/jinexus-framework-skeleton" role="button">Fork JiNexus Framework Skeleton on GitHub &raquo;</a>
            </p>
        </div>
    </div>
    <div class="container">
        <div class="card-deck">
            <div class="card border-primary box-shadow">
                <div class="card-header text-primary"><i class="fas fa-book"></i> Documentation</div>
                <div class="card-body">
                    <p class="card-text">
                        Get started with JiNexus Framework by checking its documentation.
                        This will give you the idea on how easy to set things all up.
                        Learning a new framework is hard, JF provides simple abstract and semantic interface to help developers understand this framework.
                    </p>
                </div>
                <div class="card-footer">
                    <a class="btn btn-block btn-primary" href="https://framework.jinexus.com" target="_blank" role="button">View details &raquo;</a>
                </div>
            </div>
            <div class="card border-primary box-shadow">
                <div class="card-header text-primary"><i class="fas fa-code"></i> Development Updates</div>
                <div class="card-body">
                    <p class="card-text">
                        JiNexus Framework is under active development.
                        If you are interested in following the development of JF, you may check its GitHub repositories.
                        This is a great resource for staying up to date with the latest developments!
                    </p>
                </div>
                <div class="card-footer">
                    <a class="btn btn-block btn-primary" href="https://github.com/jinexus-framework" target="_blank" role="button">View details &raquo;</a>
                </div>
            </div>
            <div class="card border-primary box-shadow">
                <div class="card-header text-primary"><i class="fab fa-osi"></i> Contributor Code of Conduct</div>
                <div class="card-body">
                    <p class="card-text">
                        JiNexus Framework is an open source project and hereby adheres to The Code Manifesto as its guidelines for contributor interactions.
                        An ecosystem that empowers developers to reach their potential — one that encourages growth and effective collaboration.
                    </p>
                </div>
                <div class="card-footer">
                    <a class="btn btn-block btn-primary" href="https://github.com/jinexus-framework/jinexus-framework-skeleton/blob/master/CONDUCT.md" target="_blank" role="button">View details &raquo;</a>
                </div>
            </div>
        </div>
        <hr>
    </div>
</main>